development:
  adapter: postgresql
  encoding: unicode
  database: englishpl_2022
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: englishpl_2022
  pool: 5
  username:
  password: