default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: englishpl_2022


test:
  <<: *default
  database: englishpl_2022

production:
  <<: *default
  database: englishpl_2022
  username:
  password: